import { invoke } from '@tauri-apps/api/core';

export type RuleSeverity = 'info' | 'warn' | 'danger';
export type RuleKind =
  | 'permission'
  | 'component'
  | 'component_class'
  | 'sdk'
  | 'manifest'
  | 'native_library'
  | 'action';

export type Rule = {
  id: string;
  description?: string | null;
  severity: RuleSeverity | string;
  kind: RuleKind | string;
  match: Record<string, unknown>;
  metadata?: Record<string, unknown> | null;
};

export type RuleSet = {
  id: string;
  name: string;
  version?: string | null;
  description?: string | null;
  rules: Rule[];
};

export type RuleResultMetadata = {
  /** Library / class / SDK display name, e.g. "Burst" or "MSA SDK". */
  label?: string | null;
  /** Vendor or maintainer (often the team / company). */
  dev_team?: string | null;
  /** Upstream URL — official docs, source link, or homepage. */
  source_link?: string | null;
  /** Chinese description from the upstream LibChecker-Rules repository. */
  zh_description?: string | null;
};

export type MatchedRule = {
  rule_set_id: string;
  rule_id: string;
  severity: string;
  description: string;
  /** Forwarded from the backend's `Rule.metadata`. Populated for
   * LibChecker-Rules hits (`{label, dev_team, source_link,
   * zh_description}`); undefined for bundled starter rules. */
  metadata?: RuleResultMetadata | null;
};

/** One APK-side component (a `.so` basename, or an Activity/Service/
 *  Receiver/Provider FQN) paired with the libchecker rule (if any)
 *  that recognised it. `matched_rule === null` means the component
 *  exists in the APK but no installed rule pack covers it. */
export type ComponentHit = {
  name: string;
  matched_rule?: MatchedRule | null;
};

/** APK-side component breakdown — one Vec per category so the UI can
 *  render five independent sections without further server work. */
export type ComponentMatches = {
  native_libraries: ComponentHit[];
  activities: ComponentHit[];
  services: ComponentHit[];
  receivers: ComponentHit[];
  providers: ComponentHit[];
};

export type RuleReport = {
  apk_path: string;
  components: ComponentMatches;
  /** Total components across all 5 categories that have a
   *  `matched_rule`. Used by the dashboard hit-count badge. */
  total_matched: number;
};

export async function listRules(): Promise<RuleSet[]> {
  return invoke<RuleSet[]>('list_rules');
}

export async function analyzeWithRules(
  apkPath: string,
  ruleSetIds: string[],
): Promise<RuleReport> {
  return invoke<RuleReport>('analyze_with_rules', { apkPath, ruleSetIds });
}

export type InstalledRulePack = {
  id: string;
  name: string;
  rule_count: number;
  version?: string | null;
};

export type RulePackSource = 'bundled' | 'server' | 'libchecker';

export type RulePackStatus = {
  installed: boolean;
  path: string | null;
  packs: InstalledRulePack[];
  total_rules: number;
  source: RulePackSource | null;
  download_url: string | null;
  libchecker_version?: number | null;
  libchecker_commit?: string | null;
  /// Last install/refresh fallback reason. `undefined` means the
  /// response was generated by a fresh install (no previous error to
  /// report) AND no fallback occurred; non-empty when the installer
  /// could not deliver an upstream (Libchecker / server) pack and
  /// shipped bundled content instead. Front-end surfaces this in the
  /// toast and an inline notice so users can tell the difference
  /// between "real LibChecker data" and "you only got the bundled
  /// starter because the network / upstream failed".
  lastError?: string | null;
};

export async function getRulePackStatus(): Promise<RulePackStatus> {
  return invoke<RulePackStatus>('get_rule_pack_status');
}

export async function installRulePacks(): Promise<RulePackStatus> {
  return invoke<RulePackStatus>('install_rule_packs');
}

export async function uninstallRulePacks(): Promise<void> {
  return invoke<void>('uninstall_rule_packs');
}

export async function installLibcheckerRules(): Promise<RulePackStatus> {
  return invoke<RulePackStatus>('install_libchecker_rules');
}
